def medical_info_tool(query: str) -> str:
    return f"""
Medical Information Tool:

You asked: '{query}'.

This is a basic educational response generated by the MediGuide AI medical information tool.
It is intended for informational purposes only and should not replace professional medical advice.
""".strip()


def home_remedy_tool(query: str) -> str:
    return f"""
Home Remedy Tool:

You asked: '{query}'.

Here are some simple home-care suggestions:
- Stay hydrated.
- Get adequate rest.
- Eat nutritious food.
- Monitor your symptoms.
- Seek professional medical care if symptoms worsen.

This is an educational response and not a substitute for medical advice.
""".strip()


def hospital_finder_tool(query: str) -> str:
    return f"""
Hospital Finder Tool:

You asked: '{query}'.

Hospital search capability will be integrated in a later phase.
For now, please use Google Maps or your local healthcare directory to locate nearby hospitals or clinics.
""".strip()