from langchain_core.tools import tool


@tool
def medical_info_tool(query: str) -> str:
    """
    Provides basic educational medical information.
    """

    return (
        f"Medical Information Tool:\n\n"
        f"You asked: '{query}'.\n\n"
        f"This is a basic educational response generated by the "
        f"MediGuide AI medical information tool."
    )